openapi: 3.1.0
info:
  version: 1.0.0
  title: nodejs-hw-mongodb
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    The app allows users to register, log in, add, edit, delete and view contacts. The application also supports integration with Google OAuth for user authorization.
tags:
  - name: Auth
    description: Operations with users (registration, login, exit, etc.)
  - name: Contacts
    description: Operations with contacts (adding, editing, deleting, viewing)
servers:
  - url: <http://localhost:3000>
  # - url: #посилання на задеплоєний сайт
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
